# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy necessary files
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages ./packages
COPY src ./src
COPY tsconfig.json ./

# Install pnpm globally
RUN npm install -g pnpm

# Install dependencies without running scripts
RUN pnpm install --ignore-scripts

# Build the project
RUN pnpm build

# Expose any port if needed (not specified, so skip)

CMD ["node", "packages/server/dist/index.js"]
